### ISSUE TITLE
Reading HCIM stats requires arg HIM but error message says to use HIC

### ISSUE THREAD

**Issue by DrewCording** [Coffee-fueled-deadlines/OSRSBytes#10]
When attempting to read stats for a hardcore, the correct argument for account type is 'HIM' (found by reading through source). But, the build-in error message when calling the function with no account type argument says to use the 'HIC' for a hardcore, which is not a correct argument for any account type and will just throw the same error. The error message and source need to be made to match. 

Additionally, neither HIC or HIM is intuitive to use. The official game mode is called HCIM.

**Comment by Coffee-fueled-deadlines** [comment]
`HIC` has been replaced with `HIM`, thank you for your input.  I'll roll it out into an update during the next release.
