### ISSUE TITLE
Entire bot crashes with any OSRSBytes error

### ISSUE THREAD

**Issue by JoshPaulie** [Coffee-fueled-deadlines/OSRSBytes#15]
Note: I'm on mobile

I'm running your package for my discord.py bot. At the smallest error, an exception is thrown and my whole bot is closed. The errors I've encountered are: a misspelled/nonexistent account lookup and when I misspelled a skill name. 

Both times an exception was thrown and the bot is closed before I can see what the error is.

**Comment by Coffee-fueled-deadlines** [comment]
This isn't really an issue with the package.  Exceptions often crash things and you would need to adapt your code in your bot to account for potential exceptions.  Try wrapping your code in a `Try/Except` and see if that helps, for instance:

```
from OSRSBytes import Hiscores

try:
    user = Hiscores("Bob Who Doesnt Exist")
except:
    print("An error occurred")
```

I wouldn't recommend using a blind catch like that, but you can specify the exact error/exception type by doing `except [errortype]` for example `except AssertionError`.  Just replace `[errortype]` with the type of error you're getting.

**Comment by JoshPaulie** [comment]
No other package crashes the bot after an excpetion. I tried the try-except, same result.

**Comment by Coffee-fueled-deadlines** [comment]
Feel free to submit your exact error in this issue and I can attempt to help you troubleshoot it.  Do note that the package is designed to throw an exception on an error and not designed to 'march on at all costs'.  Handling those exceptions and handling those errors is on the coder to integrate into their main code.

**Comment by JoshPaulie** [comment]
![crash 41](https://user-images.githubusercontent.com/30572280/133519570-44d53d2b-ba19-4add-8668-0b8653658dde.png)

> the package is designed to throw an exception on an error and not designed to 'march on at all costs'.

From what I can tell, there is no exception thrown to catch.

**Comment by Coffee-fueled-deadlines** [comment]
You appear to be using an old version of OSRSBytes.  Update it with, `pip install OSRSBytes --upgrade`

**Comment by JoshPaulie** [comment]
![image](https://user-images.githubusercontent.com/30572280/133520558-1c3a3202-0c55-4d70-8610-e0ad0e523337.png)

**Comment by Coffee-fueled-deadlines** [comment]
Attempt to uninstall your OSRSBytes package with `pip uninstall OSRSBytes`

There are times where packages can get stuck so you may have to manually delete the OSRSBytes package from the `site_packages` directory in your python installation.  It does, however, appear that you are most likely using an older version as the error message that you provided hasn't been used in awhile (refers to HIC instead of HIM).

If all else fails, attempt to install OSRSBytes into a Venv to further troubleshoot this.

**Comment by JoshPaulie** [comment]
Followed your instructions, deleted old site packages (including from OSRS-Hiscores), and with same result. I'll look into using the API myself and write my own little wrapper. Thanks for the quick replies.
