### ISSUE TITLE
Pypi hosting bugged v1.2.3 

### ISSUE THREAD

**Issue by RileyFitz** [Coffee-fueled-deadlines/OSRSBytes#17]
Pypi is still hosting v1.2.3, and this includes the bug from issue #8 . This makes the instructions on the README.md of how to install and upgrade moot to receive the newest version of 1.2.4 with the bug fixes for Hiscores modules, and version corrections.

The only way to obtain a working copy of this repo then is to install from source.

## Fix
Please update the Pypi package to v1.2.4

**Comment by Coffee-fueled-deadlines** [comment]
I'll most likely get on this over the weekend after doing a bit of work on it during the week.  There are a few other issues that really need resolved before pushing a new version to pypi.

**Comment by Coffee-fueled-deadlines** [comment]
I'll be pushing 1.3.0 to PyPi today at 1900 EST time.  If you have anything you'd like to commit, please do so before then.

**Comment by Coffee-fueled-deadlines** [comment]
Pypi is now version 1.3.0.  You may need to upgrade with `pip install --upgrade osrsbytes`
