### ISSUE TITLE
Items.update() missing from latest PyPI build

### ISSUE THREAD

**Issue by jakewalker-codes** [Coffee-fueled-deadlines/OSRSBytes#37]
Hi

The Items() class is missing the update() method in the

![image](https://user-images.githubusercontent.com/67870491/219681280-ea6ad735-2e87-46ff-a78b-60ccabb9fba3.png)

I had a look at the OSRSBytes library thats installed in my virtual environment and it's missing the update method:

![image](https://user-images.githubusercontent.com/67870491/219681910-1bfb8542-f43d-40a4-b501-b844e34de20a.png)

The Items.py file in the main and dev branch all have this method though and adding the snippet from the repo to the Items.py file in my virtual environment fixed this issue.

I installed the OSRSBytes library by running the pip install command

upgrading, uninstalling and reinstalling using pip did not fix the issue

I am running version 1.3.0 of OSRSBytes

Thanks,

**Comment by Coffee-fueled-deadlines** [comment]
Correct.  I believe at some point Dev got merged into Master unintentionally.  `Update()` will be added in the 1.3.1 release.  In addition, an easy work around would be to just initialize `Items()` again as such:

```
i = Items()

# do some stuff
i.isMembers("rune dagger")

# update items again
i = Items()
```

**Comment by jakewalker-codes** [comment]
Thanks for your speedy response! :)

**Comment by Coffee-fueled-deadlines** [comment]
Not a problem, thank you for the report.
