### ISSUE TITLE
hiscores indexing issues:

### ISSUE THREAD

**Issue by johnnydhnguyen** [Coffee-fueled-deadlines/OSRSBytes#38]
I've noticed that whilst running a for through each boss name in the dictionary provided in the code, everything after obor shifts one index to the right.

After debugging, I found that this may be due to the phantom muspah update has caused an issue in indexing when calling onto the osrs hiscores api.

**Comment by Coffee-fueled-deadlines** [comment]
> I've noticed that whilst running a for through each boss name in the dictionary provided in the code, everything after obor shifts one index to the right.
> 
> 
> 
> After debugging, I found that this may be due to the phantom muspah update has caused an issue in indexing when calling onto the osrs hiscores api. 

Thank you for pointing this out. I had a feeling that this would be something that would, honestly, come to be common-place due to jagex's janky excuse for a hiscores page. 

I'll push out a fix this weekend.

**Comment by johnnydhnguyen** [comment]
I fixed the issue on my end, what you can do is to go into hiscores.py

right under "obor" in the parseBosses function, add in "phantom_muspah". Should fix the issue instantly.

**Comment by Coffee-fueled-deadlines** [comment]
Fixed as of [this](https://github.com/Coffee-fueled-deadlines/OSRSBytes/commit/38b190286693f853247a1de317ea8d804d2c09ab) commit.
