### ISSUE TITLE
New Hiscores API update | Bosses list

### ISSUE THREAD

**Issue by johnnydhnguyen** [Coffee-fueled-deadlines/OSRSBytes#40]
Hi, there's a new bug again. Jagex added Artio, Calvar'ion and Spindel to the hiscores. Here is the updated self.__bosses list:

self.__bosses = [
			"rifts_closed",
			"abyssal_sire",
			"alchemical_hydra",
			"artio"
			"barrows_chests",
			"bryophyta",
			"callisto",
			"calvar'ion",
			"cerberus",
			"chambers_of_xeric",
			"chambers_of_xeric_challenge",
			"chaos_elemental",
			"chaos_fanatic",
			"commander_zilyana",
			"corporeal_beast",
			"crazy_archaeologist",
			"dagannoth_prime",
			"dagannoth_rex",
			"dagannoth_supreme",
			"deranged_archaeologist",
			"general_graardor",
			"giant_mole",
			"grotesque_guardians",
			"hesporti",
			"kalphite_queen",
			"king_black_dragon",
			"kraken",
			"kreearra",
			"kril_tsutsaroth",
			"mimic",
			"nex",
			"nightmare",
			"phosanis_nightmare",
			"obor",
			"phantom_muspah",
			"sarachnis",
			"scorpia",
			"skotizo",
			"spindel",
			"tempoross",
			"gauntlet",
			"corrupted_gauntlet",
			"theatre_of_blood",
			"theatre_of_blood_hard",
			"thermonuclear_smoke_devil",
			"tombs_of_amascut",
			"tombs_of_amascut_expert",
			"zuk",
			"jad",
			"venenatis",
			"vetion",
			"vorkath",
			"wintertodt",
			"zalcano",
			"zulrah"
		]

**Comment by Coffee-fueled-deadlines** [comment]
I intend to work through this today and through the weekend to come up with a solution that doesn't involve constantly manually updating the boss list.
