### ISSUE TITLE
Problem with library

### ISSUE THREAD

**Issue by Endorosaurus** [Coffee-fueled-deadlines/OSRSBytes#7]
This is most likely a problem with the website, but it shows rune dagger price as 0. All other prices are normal though.

**Comment by Coffee-fueled-deadlines** [comment]
```python
from OSRSBytes import Items
item = Items()

buy_value      = item.getBuyAverage('rune dagger')
buy_quantity = item.getBuyQuantity('rune dagger')

print(buy_value)
print(buy_quantity)
```

Issue isn't with the website nor is the issue with OSRSBytes, what you're experiencing is the OSRS Market as seen by OSBuddy.  No one is currently buying `rune dagger` and thus there are `0` buy orders for it.  Because there are `0` buy orders for it, the `buy_average` is 0.
